use std::collections::HashMap;

use super::dice::cbor::{
    generate_pubkey_hash_value_buffer, parse_claims_buffer, parse_evidence_buffer_with_tag,
};
use super::dice::extensions::{OID_TCG_DICE_ENDORSEMENT_MANIFEST, OID_TCG_DICE_TAGGED_EVIDENCE};
use super::CLAIM_NAME_PUBLIC_KEY_HASH;
use crate::crypto::DefaultCrypto;
use crate::crypto::HashAlgo;
use crate::errors::*;
use crate::tee::auto::{AutoEvidence, AutoVerifier, LocalEvidence};
use crate::tee::coco::converter::CocoConverter;
use crate::tee::coco::evidence::{CocoAsToken, CocoEvidence};
use crate::tee::coco::verifier::CocoVerifier;
use crate::tee::{claims::Claims, GenericEvidence, GenericVerifier};
use crate::tee::{GenericConverter, ReportData};

use anyhow::Context;
use base64::prelude::BASE64_STANDARD;
use base64::Engine;
use const_oid::ObjectIdentifier;
use pkcs8::der::referenced::OwnedToRef;
use pkcs8::der::{Decode, DecodePem, Encode};
use pkcs8::spki::AlgorithmIdentifierOwned;
use signature::Verifier;
use x509_cert::Certificate;

/// Trait representing verification policies that can be applied to certificates.
pub trait VerifyPolicy: Send + Sync {
    /// The processed evidence type that implements GenericEvidence
    type ProcessedEvidence: GenericEvidence;

    /// Process the evidence and return the token (if needed)
    fn process_evidence(
        &self,
        cbor_tag: u64,
        raw_evidence: &[u8],
    ) -> impl std::future::Future<Output = Result<Self::ProcessedEvidence>> + Send;

    /// Verify the processed evidence with report data
    fn verify(
        &self,
        evidence: &Self::ProcessedEvidence,
        report_data: &ReportData,
    ) -> impl std::future::Future<Output = Result<()>> + Send;
}

/// Local verification policy
pub struct LocalVerifyPolicy;

/// CoCo verification policy
pub struct CocoVerifyPolicy {
    /// The verify mode to select
    pub verify_mode: CocoVerifyMode,
    /// The policy ids needed to check
    pub policy_ids: Vec<String>,
    /// The path of all trusted certs to be used for checking CoCo AS token
    pub trusted_certs_paths: Option<Vec<String>>,
}

pub enum CocoVerifyMode {
    /// Expect to receive a CoCo evidence (generated by attestation-agent from attester side) and verify it with CoCo attestation-service
    Evidence {
        /// The address of CoCo Attestation Service
        as_addr: String,
        /// If true, connect to Attestation Service via Grpc protocol. If false, connect via HTTP protocol.
        as_is_grpc: bool,
        /// Custom headers to be sent with attestation service requests
        as_headers: HashMap<String, String>,
    },
    /// Expect to receive a CoCo token and verify the token directly.
    Token,
}

#[allow(dead_code)]
pub struct CertVerifier<P: VerifyPolicy> {
    policy: P,
}

#[allow(dead_code)]
impl<P: VerifyPolicy> CertVerifier<P> {
    pub fn new(policy: P) -> Self {
        Self { policy }
    }

    pub async fn verify_pem(self, cert: &[u8]) -> Result<<P as VerifyPolicy>::ProcessedEvidence> {
        let cert = Certificate::from_pem(cert)
            .kind(ErrorKind::ParseCertError)
            .context("failed to parse certificate from pem")?;
        self.verify_cert(&cert).await
    }

    pub async fn verify_der(self, cert: &[u8]) -> Result<<P as VerifyPolicy>::ProcessedEvidence> {
        let cert = Certificate::from_der(cert)
            .kind(ErrorKind::ParseCertError)
            .context("failed to parse certificate from der")?;
        self.verify_cert(&cert).await
    }

    async fn verify_cert(
        &self,
        cert: &Certificate,
    ) -> Result<<P as VerifyPolicy>::ProcessedEvidence> {
        /* check self-signed cert */
        verify_cert_signature(&cert, &cert).kind(ErrorKind::CertVerifySignatureFailed)?;

        /* Extract the evidence_buffer and endorsements_buffer(optional) from the X.509 certificate extension. */
        let evidence_buffer = extract_ext_with_oid(&cert, &OID_TCG_DICE_TAGGED_EVIDENCE);
        let _endorsements_buffer = extract_ext_with_oid(&cert, &OID_TCG_DICE_ENDORSEMENT_MANIFEST);

        /* evidence extension is not optional */
        let evidence_buffer = match evidence_buffer {
            Some(v) => v,
            None => Err(Error::kind_with_msg(
                ErrorKind::CertExtractExtensionFailed,
                "failed to extract the evidence extensions from the certificate",
            ))?,
        };
        /* endorsements extension is optional */
        // TODO: endorsements extension

        let (cbor_tag, raw_evidence, _) = parse_evidence_buffer_with_tag(evidence_buffer)?;
        // Note: the implementation here is not compatible with the Interoperable RA-TLS now

        /* Prepare expected pubkey-hash claim */
        let spki_bytes = cert.tbs_certificate.subject_public_key_info.to_der()?;
        // TODO: Hash algorithm is currently hardcoded to SHA256.
        // Future support should include extracting the hash algorithm from the evidence.
        let pubkey_hash = DefaultCrypto::hash(HashAlgo::Sha256, &spki_bytes);
        let pubkey_hash_value_buffer =
            generate_pubkey_hash_value_buffer(HashAlgo::Sha256, &pubkey_hash)?;

        let mut expected_claims = Claims::new();
        expected_claims.insert(
            CLAIM_NAME_PUBLIC_KEY_HASH.into(),
            serde_json::Value::String(BASE64_STANDARD.encode(pubkey_hash_value_buffer)),
        );
        let report_data = ReportData::Claims(expected_claims);

        /* Process and verify evidence using the policy */
        let evidence = self
            .policy
            .process_evidence(cbor_tag, &raw_evidence)
            .await?;
        self.policy.verify(&evidence, &report_data).await?;

        Ok(evidence)
    }
}

// Implementation of LocalVerifyPolicy
impl VerifyPolicy for LocalVerifyPolicy {
    type ProcessedEvidence = AutoEvidence;

    async fn process_evidence(
        &self,
        cbor_tag: u64,
        raw_evidence: &[u8],
    ) -> Result<Self::ProcessedEvidence> {
        let evidence = Into::<Result<_>>::into(AutoEvidence::create_evidence_from_dice(
            cbor_tag,
            raw_evidence,
        ))
        .with_context(|| {
            format!(
                "Failed to parse evidence: cbor_tag: {:#x?}, raw_evidence: {:02x?}...({}bytes)",
                cbor_tag,
                &raw_evidence[..10],
                raw_evidence.len()
            )
        })?;
        let tee_type = evidence.get_tee_type();
        tracing::debug!("TEE type of this cert is {:?}", tee_type);
        Ok(evidence)
    }

    async fn verify(
        &self,
        evidence: &Self::ProcessedEvidence,
        report_data: &ReportData,
    ) -> Result<()> {
        let verifier = AutoVerifier::new();
        verifier.verify_evidence(evidence, report_data).await?;
        Ok(())
    }
}

// Implementation of CocoVerifyPolicy
impl VerifyPolicy for CocoVerifyPolicy {
    type ProcessedEvidence = CocoAsToken;

    async fn process_evidence(
        &self,
        cbor_tag: u64,
        raw_evidence: &[u8],
    ) -> Result<Self::ProcessedEvidence> {
        let token = match &self.verify_mode {
            CocoVerifyMode::Evidence {
                as_addr,
                as_is_grpc,
                as_headers,
            } => {
                let evidence = Into::<Result<_>>::into(CocoEvidence::create_evidence_from_dice(
                    cbor_tag,
                    raw_evidence,
                ))
                .with_context(|| {
                    format!(
                        "Failed to parse CoCo evidence: cbor_tag: {:#x?}, raw_evidence: {:02x?}...({}bytes)",
                        cbor_tag, &raw_evidence[..10],raw_evidence.len()
                    )
                })?;
                tracing::debug!("Creating CocoConverter now. as_addr: {as_addr}, policy_ids: {:?}, as_is_grpc: {}", &self.policy_ids, *as_is_grpc );
                let converter =
                    CocoConverter::new(&as_addr, &self.policy_ids, *as_is_grpc, as_headers)?;
                converter.convert(&evidence).await?
            }
            CocoVerifyMode::Token => {
                let token = Into::<Result<_>>::into(CocoAsToken::create_evidence_from_dice(
                    cbor_tag,
                    raw_evidence,
                ))
                .with_context(|| {
                    format!(
                        "Failed to parse CoCo AS token: cbor_tag: {:#x?}, raw_evidence: {:02x?}...({}bytes)",
                        cbor_tag, &raw_evidence[..10],raw_evidence.len()
                    )
                })?;
                token
            }
        };
        Ok(token)
    }

    async fn verify(
        &self,
        evidence: &Self::ProcessedEvidence,
        report_data: &ReportData,
    ) -> Result<()> {
        let verifier = CocoVerifier::new(&self.trusted_certs_paths, &self.policy_ids).await?;
        verifier.verify_evidence(evidence, report_data).await?;
        Ok(())
    }
}

fn verify_cert_signature(issuer: &Certificate, signed: &Certificate) -> Result<()> {
    if issuer.tbs_certificate.subject != signed.tbs_certificate.issuer {
        return Err("certificate issuer does not match".into());
    }

    let signed_data = signed.tbs_certificate.to_der()?;
    let signature = signed
        .signature
        .as_bytes()
        .ok_or("could not get cert signature")?;

    verify_signed_data(issuer, &signed_data, signature, &signed.signature_algorithm)
}

fn verify_signed_data(
    issuer: &Certificate,
    signed_data: &[u8],
    signature: &[u8],
    algo: &AlgorithmIdentifierOwned,
) -> Result<()> {
    let spki = issuer
        .tbs_certificate
        .subject_public_key_info
        .owned_to_ref();

    match algo.oid {
        const_oid::db::rfc5912::SHA_256_WITH_RSA_ENCRYPTION => {
            rsa::pkcs1v15::VerifyingKey::<sha2::Sha256>::new(rsa::RsaPublicKey::try_from(spki)?)
                .verify(signed_data, &signature.try_into()?)?;
        }
        const_oid::db::rfc5912::SHA_384_WITH_RSA_ENCRYPTION => {
            rsa::pkcs1v15::VerifyingKey::<sha2::Sha384>::new(rsa::RsaPublicKey::try_from(spki)?)
                .verify(signed_data, &signature.try_into()?)?;
        }
        const_oid::db::rfc5912::SHA_512_WITH_RSA_ENCRYPTION => {
            rsa::pkcs1v15::VerifyingKey::<sha2::Sha512>::new(rsa::RsaPublicKey::try_from(spki)?)
                .verify(signed_data, &signature.try_into()?)?;
        }

        const_oid::db::rfc5912::ECDSA_WITH_SHA_256 => {
            let signature = p256::ecdsa::DerSignature::try_from(signature)?;
            p256::ecdsa::VerifyingKey::try_from(spki)?.verify(signed_data, &signature)?;
        }

        _ => {
            return Err(format!(
                "unknown signature algo {}",
                issuer.tbs_certificate.signature.oid
            )
            .into())
        }
    }

    Ok(())
}

fn extract_ext_with_oid<'a>(cert: &'a Certificate, oid: &ObjectIdentifier) -> Option<&'a [u8]> {
    cert.tbs_certificate
        .extensions
        .as_ref()
        .map(|exts| {
            let mut it = exts.iter().filter(|ext| ext.extn_id == *oid);
            if let Some(ext) = it.next() {
                return Some(ext.extn_value.as_bytes());
            } else {
                return None;
            }
        })
        .flatten()
}

#[cfg(test)]
pub mod tests {

    use crate::{
        cert::create::CertBuilder,
        crypto::{AsymmetricAlgo, HashAlgo},
        errors::*,
        tee::{
            auto::AutoAttester,
            claims::{Claims, BUILT_IN_CLAIM_COMMON_TEE_TYPE},
            TeeType,
        },
    };

    #[allow(unused_imports)]
    use super::*;

    #[tokio::test]
    async fn test_verify_attestation_certificate() -> Result<()> {
        if TeeType::detect_env() == None {
            /* skip */
            return Ok(());
        }

        /* Test verify normal cert */
        let mut claims = Claims::new();
        claims.insert("key1".into(), "value1".into());
        claims.insert("key2".into(), "value2".into());

        let attester = AutoAttester::new();
        let cert_bundle = CertBuilder::new(attester, HashAlgo::Sha256)
            .with_claims(claims.clone())
            .build(AsymmetricAlgo::P256)
            .await?;
        let cert = cert_bundle.cert_to_der()?;
        CertVerifier::new(LocalVerifyPolicy)
            .verify_der(&cert)
            .await?;

        Ok(())
    }

    #[tokio::test]
    async fn test_verify_attestation_certificate_with_claims_overriding() -> Result<()> {
        if TeeType::detect_env() == None {
            /* skip */
            return Ok(());
        }

        /* Test verify cert with claims overriding */
        let mut claims = Claims::new();
        claims.insert(
            BUILT_IN_CLAIM_COMMON_TEE_TYPE.into(),
            "test-tee-type".into(),
        ); /* Try to overriding the "common_quote_type" claim */

        let attester = AutoAttester::new();
        let cert_bundle = CertBuilder::new(attester, HashAlgo::Sha256)
            .with_claims(claims.clone())
            .build(AsymmetricAlgo::P256)
            .await?;
        let cert = cert_bundle.cert_to_der()?;

        CertVerifier::new(LocalVerifyPolicy)
            .verify_der(&cert)
            .await?;

        Ok(())
    }
}
