// This file is generated by ttrpc-compiler 0.6.2. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unknown_lints)]
#![allow(clipto_camel_casepy)]
#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
#![allow(clippy::all)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;

#[derive(Clone)]
pub struct AttestationAgentServiceClient {
    client: ::ttrpc::Client,
}

impl AttestationAgentServiceClient {
    pub fn new(client: ::ttrpc::Client) -> Self {
        AttestationAgentServiceClient {
            client: client,
        }
    }

    pub fn get_evidence(&self, ctx: ttrpc::context::Context, req: &super::attestation_agent::GetEvidenceRequest) -> ::ttrpc::Result<super::attestation_agent::GetEvidenceResponse> {
        let mut cres = super::attestation_agent::GetEvidenceResponse::new();
        ::ttrpc::client_request!(self, ctx, req, "attestation_agent.AttestationAgentService", "GetEvidence", cres);
        Ok(cres)
    }

    pub fn get_tee_type(&self, ctx: ttrpc::context::Context, req: &super::attestation_agent::GetTeeTypeRequest) -> ::ttrpc::Result<super::attestation_agent::GetTeeTypeResponse> {
        let mut cres = super::attestation_agent::GetTeeTypeResponse::new();
        ::ttrpc::client_request!(self, ctx, req, "attestation_agent.AttestationAgentService", "GetTeeType", cres);
        Ok(cres)
    }
}

struct GetEvidenceMethod {
    service: Arc<Box<dyn AttestationAgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for GetEvidenceMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, attestation_agent, GetEvidenceRequest, get_evidence);
        Ok(())
    }
}

struct GetTeeTypeMethod {
    service: Arc<Box<dyn AttestationAgentService + Send + Sync>>,
}

impl ::ttrpc::MethodHandler for GetTeeTypeMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, attestation_agent, GetTeeTypeRequest, get_tee_type);
        Ok(())
    }
}

pub trait AttestationAgentService {
    fn get_evidence(&self, _ctx: &::ttrpc::TtrpcContext, _: super::attestation_agent::GetEvidenceRequest) -> ::ttrpc::Result<super::attestation_agent::GetEvidenceResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/attestation_agent.AttestationAgentService/GetEvidence is not supported".to_string())))
    }
    fn get_tee_type(&self, _ctx: &::ttrpc::TtrpcContext, _: super::attestation_agent::GetTeeTypeRequest) -> ::ttrpc::Result<super::attestation_agent::GetTeeTypeResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/attestation_agent.AttestationAgentService/GetTeeType is not supported".to_string())))
    }
}

pub fn create_attestation_agent_service(service: Arc<Box<dyn AttestationAgentService + Send + Sync>>) -> HashMap<String, Box<dyn ::ttrpc::MethodHandler + Send + Sync>> {
    let mut methods = HashMap::new();

    methods.insert("/attestation_agent.AttestationAgentService/GetEvidence".to_string(),
                    Box::new(GetEvidenceMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/attestation_agent.AttestationAgentService/GetTeeType".to_string(),
                    Box::new(GetTeeTypeMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods
}
