use std::collections::HashMap;

use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use base64::prelude::BASE64_STANDARD;
use base64::Engine as _;
use flatten_json_object::Flattener;
use serde::{Deserialize, Serialize};
use serde_bytes::ByteBuf;
use serde_json::{json, Value};

use crate::cert::dice::cbor::{
    HashAlgoIanaId, OCBR_TAG_EVIDENCE_COCO_EVIDENCE, OCBR_TAG_EVIDENCE_COCO_TOKEN,
};
use crate::crypto::HashAlgo;
use crate::errors::*;
use crate::tee::claims::Claims;
use crate::tee::coco::converter::AttestationServiceHashAlgo;
use crate::tee::{DiceParseEvidenceOutput, GenericEvidence, ReportData};

#[derive(Clone, PartialEq, Eq, Hash)]
pub(crate) struct AaTeeType(String);

impl AaTeeType {
    pub fn as_attestation_service_str_id(&self) -> &str {
        match self.0.as_str() {
            // AA is using "sgx-dcap" while "sgx" is required in AS. See https://github.com/confidential-containers/trustee/blob/09bef2e2a53d54c2d3107635a65337f409eeaebe/attestation-service/attestation-service/src/bin/grpc/mod.rs#L29-L41
            "sgx-dcap" => "sgx",
            v => v,
        }
    }

    pub fn as_attestation_agent_str_id(&self) -> &str {
        &self.0
    }

    pub fn from_attestation_agent_str_id(tee_type_str: impl Into<String>) -> Self {
        Self(tee_type_str.into())
    }
}

pub struct CocoEvidence {
    pub(self) aa_tee_type: AaTeeType,
    /// Raw evidence generated by attestation-agent
    pub(self) aa_evidence: HashMap<AaTeeType, Vec<u8>>,
    /// The structed runtime data json which is passed to attestation-agent for generating the evidence, should be hashed with aa_runtime_data_algo.
    pub(self) aa_runtime_data: String,
    /// The hash algorithm used for calculating hash of aa_runtime_data.
    pub(self) aa_runtime_data_hash_algo: HashAlgo,
}

impl CocoEvidence {
    #[allow(unused)]
    pub(crate) fn new(
        aa_tee_type: AaTeeType,
        aa_evidence: HashMap<AaTeeType, Vec<u8>>,
        aa_runtime_data: String,
        aa_runtime_data_hash_algo: HashAlgo,
    ) -> Result<Self> {
        Ok(Self {
            aa_tee_type,
            aa_evidence,
            aa_runtime_data,
            aa_runtime_data_hash_algo,
        })
    }

    pub(crate) fn get_tee_type(&self) -> &AaTeeType {
        &self.aa_tee_type
    }

    pub(crate) fn aa_evidence_ref(&self) -> &HashMap<AaTeeType, Vec<u8>> {
        &self.aa_evidence
    }

    pub(crate) fn aa_runtime_data_ref(&self) -> &str {
        &self.aa_runtime_data
    }

    pub(crate) fn get_aa_runtime_data_hash_algo(&self) -> HashAlgo {
        self.aa_runtime_data_hash_algo
    }

    pub(crate) fn wrap_runtime_data_as_structed(
        report_data: &ReportData,
    ) -> Result<serde_json::Value> {
        match report_data {
            ReportData::Raw(report_data) => {
                Ok(json!({"rats-rs.raw_runtime_data": URL_SAFE_NO_PAD.encode(report_data)}))
            }
            ReportData::Claims(claims) => serde_json::to_value(claims),
        }
        .context("Failed to construct structed runtime data")
    }

    pub fn serialize_to_json(&self) -> serde_json::Result<serde_json::Value> {
        Ok(serde_json::to_value(self.into_json_helper())?)
    }

    pub fn deserialize_from_json(value: serde_json::Value) -> Result<Self> {
        Ok(Self::from_json_helper(serde_json::from_value::<
            CocoEvidenceJsonHelper,
        >(value)?)?)
    }
}

impl GenericEvidence for CocoEvidence {
    fn get_dice_cbor_tag(&self) -> u64 {
        return OCBR_TAG_EVIDENCE_COCO_EVIDENCE;
    }

    fn get_dice_raw_evidence(&self) -> Result<Vec<u8>> {
        let mut res = vec![];
        ciborium::into_writer(&self.into_cbor_helper(), &mut res)?;
        Ok(res)
    }

    fn get_claims(&self) -> Result<Claims> {
        // Return empty claims here since the structure of AA evidence is opaque.
        Ok(Claims::default())
    }

    fn create_evidence_from_dice(
        cbor_tag: u64,
        raw_evidence: &[u8],
    ) -> DiceParseEvidenceOutput<Self> {
        if cbor_tag == OCBR_TAG_EVIDENCE_COCO_EVIDENCE {
            match ciborium::from_reader::<CocoEvidenceCborHelper, _>(raw_evidence)
                .context("Failed to deserialize coco evidence")
                .and_then(|helper| CocoEvidence::from_cbor_helper(helper))
            {
                Ok(v) => DiceParseEvidenceOutput::Ok(v),
                Err(e) => DiceParseEvidenceOutput::MatchButInvalid(e.into()),
            }
        } else {
            DiceParseEvidenceOutput::NotMatch
        }
    }
}

pub struct CocoAsToken {
    data: String,
}

impl CocoAsToken {
    /// Create a new CocoAsToken instance from a attestation result JWT.
    pub fn new(token: String) -> Result<Self> {
        Ok(Self { data: token })
    }

    /// Get the attestation result JWT as a string reference
    pub fn as_str(&self) -> &str {
        &self.data
    }

    /// Get the attestation result JWT as a owned string
    pub fn into_str(self) -> String {
        self.data
    }

    pub fn exp(&self) -> Result<u64> {
        let split_token: Vec<&str> = self.data.split('.').collect();
        if !split_token.len() == 3 {
            return Err(Error::msg("Illegal JWT format"));
        }

        let claims = URL_SAFE_NO_PAD.decode(split_token[1])?;
        let claims_value = serde_json::from_slice::<Value>(&claims)?;

        let Some(exp) = claims_value["exp"].as_u64() else {
            return Err(Error::msg("token expiration unset"));
        };

        Ok(exp)
    }
}

impl GenericEvidence for CocoAsToken {
    fn get_dice_cbor_tag(&self) -> u64 {
        return OCBR_TAG_EVIDENCE_COCO_TOKEN;
    }

    fn get_dice_raw_evidence(&self) -> Result<Vec<u8>> {
        Ok(self.data.as_bytes().to_owned())
    }

    fn get_claims(&self) -> Result<Claims> {
        let split_token: Vec<&str> = self.data.split('.').collect();
        if !split_token.len() == 3 {
            return Err(Error::kind_with_msg(
                ErrorKind::CocoVerifyTokenFailed,
                "Illegal JWT format",
            ));
        }
        let claims = URL_SAFE_NO_PAD.decode(split_token[1])?;
        let claims_value = {
            let mut claims_value =
                serde_json::from_slice::<serde_json::Map<String, Value>>(&claims)?;

            if let Some(tcb_status) = claims_value.get("tcb-status") {
                if let Value::String(json_str) = tcb_status {
                    let tcb_status_claims = serde_json::from_str::<Value>(json_str);
                    match tcb_status_claims {
                        Ok(tcb_status_claims) => {
                            claims_value.insert("tcb-status".to_string(), tcb_status_claims);
                        }
                        Err(error) => {
                            tracing::warn!(?error, "failed to parse tcb-status field")
                        }
                    }
                }
            }
            Value::Object(claims_value)
        };

        let flattened_claims_value = Flattener::new()
            .flatten(&claims_value)
            .context("Failed to flatten JWT claims JSON object")?;

        Ok(match flattened_claims_value {
            Value::Object(m) => m,
            _ => {
                return Err(Error::kind_with_msg(
                    ErrorKind::CocoParseTokenFailed,
                    format!("Invalid claims value: {}", claims_value),
                ))
            }
        })
    }

    fn create_evidence_from_dice(
        cbor_tag: u64,
        raw_evidence: &[u8],
    ) -> DiceParseEvidenceOutput<Self> {
        if cbor_tag == OCBR_TAG_EVIDENCE_COCO_TOKEN {
            return match std::str::from_utf8(raw_evidence)
                .context("Failed to parse evidence as utf-8 string")
                .map(|token| Self::new(token.to_owned()))
            {
                Ok(Ok(v)) => DiceParseEvidenceOutput::Ok(v),
                Ok(Err(e)) => DiceParseEvidenceOutput::MatchButInvalid(e),
                Err(e) => DiceParseEvidenceOutput::MatchButInvalid(e.into()),
            };
        }
        return DiceParseEvidenceOutput::NotMatch;
    }
}

#[derive(Serialize, Deserialize)]
struct CocoEvidenceCborHelper {
    pub(self) tee_type: String,
    pub(self) aa_evidence: ByteBuf,
    pub(self) aa_runtime_data: String,
    pub(self) aa_runtime_data_hash_algo: HashAlgoIanaId,
}

impl CocoEvidence {
    fn into_cbor_helper(&self) -> CocoEvidenceCborHelper {
        // Serialize HashMap<AaTeeType, Vec<u8>> to HashMap<String, Vec<u8>> for CBOR
        let evidence_map: HashMap<String, Vec<u8>> = self
            .aa_evidence
            .iter()
            .map(|(k, v)| (k.as_attestation_agent_str_id().to_owned(), v.clone()))
            .collect();
        let evidence_bytes = serde_json::to_vec(&evidence_map).unwrap_or_default();
        CocoEvidenceCborHelper {
            tee_type: self.aa_tee_type.as_attestation_agent_str_id().to_owned(),
            aa_evidence: ByteBuf::from(evidence_bytes),
            aa_runtime_data: self.aa_runtime_data.to_owned(),
            aa_runtime_data_hash_algo: self.aa_runtime_data_hash_algo.into(),
        }
    }

    fn from_cbor_helper(helper: CocoEvidenceCborHelper) -> Result<Self> {
        let evidence_map: HashMap<String, Vec<u8>> =
            serde_json::from_slice(&helper.aa_evidence.into_vec())
                .context("Failed to deserialize aa_evidence from CBOR")?;
        let aa_evidence: HashMap<AaTeeType, Vec<u8>> = evidence_map
            .into_iter()
            .map(|(k, v)| (AaTeeType::from_attestation_agent_str_id(&k), v))
            .collect();
        Ok(Self {
            aa_tee_type: AaTeeType::from_attestation_agent_str_id(&helper.tee_type),
            aa_evidence,
            aa_runtime_data: helper.aa_runtime_data,
            aa_runtime_data_hash_algo: helper.aa_runtime_data_hash_algo.try_into()?,
        })
    }
}

#[derive(Serialize, Deserialize)]
struct CocoEvidenceJsonHelper {
    pub(self) aa_tee_type: String,
    // Base64 encoded
    pub(self) aa_evidence: HashMap<String, String>,
    pub(self) aa_runtime_data: String,
    pub(self) aa_runtime_data_hash_algo: AttestationServiceHashAlgo,
}

impl CocoEvidence {
    fn into_json_helper(&self) -> CocoEvidenceJsonHelper {
        CocoEvidenceJsonHelper {
            aa_tee_type: self.aa_tee_type.as_attestation_agent_str_id().to_owned(),

            aa_evidence: self
                .aa_evidence
                .iter()
                .map(|(k, v)| {
                    (
                        k.as_attestation_agent_str_id().to_owned(),
                        BASE64_STANDARD.encode(v),
                    )
                })
                .collect(),
            aa_runtime_data: self.aa_runtime_data.clone(),
            aa_runtime_data_hash_algo: self.aa_runtime_data_hash_algo.into(),
        }
    }

    fn from_json_helper(helper: CocoEvidenceJsonHelper) -> Result<Self> {
        let aa_evidence: HashMap<AaTeeType, Vec<u8>> = helper
            .aa_evidence
            .into_iter()
            .map(|(k, v)| {
                BASE64_STANDARD
                    .decode(v)
                    .map(|decoded| (AaTeeType::from_attestation_agent_str_id(&k), decoded))
            })
            .collect::<std::result::Result<HashMap<AaTeeType, Vec<u8>>, _>>()
            .context("Failed to decode base64 evidence")?;
        Ok(Self {
            aa_tee_type: AaTeeType::from_attestation_agent_str_id(&helper.aa_tee_type),
            aa_evidence,
            aa_runtime_data: helper.aa_runtime_data,
            aa_runtime_data_hash_algo: helper.aa_runtime_data_hash_algo.into(),
        })
    }
}
