// Taken from https://github.com/confidential-containers/guest-components/blob/3e321fd8ff65ba84e666b192ca854d306a3c613e/attestation-agent/protos/attestation-agent.proto

syntax = "proto3";

package attestation_agent;

message GetCompositeEvidenceRequest {
    bytes RuntimeData = 1;
}

message GetCompositeEvidenceResponse {
    map<string, bytes> Evidence = 1;
}

message GetTeeTypeRequest {}

message GetTeeTypeResponse {
    string tee = 1;
}

service AttestationAgentService {
    rpc GetCompositeEvidence(GetCompositeEvidenceRequest) returns (GetCompositeEvidenceResponse) {};
    rpc GetTeeType(GetTeeTypeRequest) returns (GetTeeTypeResponse) {};
}
