[package]
authors = ["Kun Lai <me@imlk.top>"]
description = "C API exported by rats-rs"
edition.workspace = true
license.workspace = true
name = "c-api"
version.workspace = true

[dependencies]
ctor = "0.2.9"
once_cell = {workspace = true}
rats-cert = {path = "../rats-cert", default-features = false, features = ["crypto-rustcrypto"]}
shadow-rs = "=0.20.1"
zeroize = {workspace = true}

[build-dependencies]
cbindgen = "0.28.0"
shadow-rs = "=0.20.1"

[features]
coco = ["rats-cert/attester-coco", "rats-cert/verifier-coco"]
default = ["local", "coco"]
local = ["rats-cert/all-attesters", "rats-cert/all-verifiers"]

[lib]
crate-type = ["cdylib", "staticlib"]
name = "rats_rs"
