name: Testing

on: [push, pull_request]

jobs:
  build-and-test:
    container: ghcr.io/inclavare-containers/rats-rs:builder

    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Prepare repo
        run:
          git config --global --add safe.directory `pwd` && just prepare-repo-spdm
        env:
          HOME: /root

      - name: Compile rats-rs (rust lib)
        run:
          just build
        env:
          HOME: /root

      - name: Compile rats-rs (C API)
        run:
          just build-c-api
        env:
          HOME: /root

      - name: Compile rats-rs (example/spdm)
        run:
          just build-example-spdm
        env:
          HOME: /root

      - name: Compile rats-rs (example/cert-app)
        run:
          just build-example-cert-app
        env:
          HOME: /root

      - name: Run unit test ${{ github.repository }}
        run:
          just run-test-in-host
        env:
          HOME: /root
