name: Testing

on: [push, pull_request]

jobs:
  build-and-test:
    container: ghcr.io/inclavare-containers/rats-rs:master

    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Prepare repo
        run:
          git config --global --add safe.directory `pwd` && just prepare-repo
        env:
          HOME: /root

      - name: Compile rats-rs (rust lib)
        run:
          cargo build --package rats-rs
        env:
          HOME: /root

      - name: Compile rats-rs (C API)
        run:
          cmake -Hc-api -Bbuild && make -Cbuild all && make -Cbuild install
        env:
          HOME: /root

      - name: Compile rats-rs (example/spdm)
        run:
          cargo build --bin spdm
        env:
          HOME: /root

      - name: Run unit test ${{ github.repository }}
        run:
          just run-test-in-host
        env:
          HOME: /root
